# Generated by Django 3.2.5 on 2021-10-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='username',
            new_name='user_id',
        ),
    ]
