# Generated by Django 3.2.5 on 2021-10-08 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='imgUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.schedule'),
        ),
    ]
